### ISSUE TITLE
Task details button is truncated in Chrome, but not Firefox

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#645]
Task details button is truncated in Chrome, but not Firefox

Chrome:
<img width="1156" alt="screen shot 2017-09-28 at 2 15 11 pm" src="https://user-images.githubusercontent.com/5589919/30983198-b4c5be32-a457-11e7-9a95-25764bdccd37.png">

Firefox:
<img width="1280" alt="screen shot 2017-09-28 at 2 15 27 pm" src="https://user-images.githubusercontent.com/5589919/30983214-bba0641e-a457-11e7-9307-c5de79e4341e.png">

@gnehapk @Tendrl/tendrl-frontend @nthomas-redhat @Tendrl/tendrl-qe @mcarrano

**Comment by mcarrano** [comment]
I have seen a similar effect on the Cluster Detail pages. 

![screen shot 2017-09-28 at 2 28 06 pm](https://user-images.githubusercontent.com/6619860/30983813-813f1f16-a459-11e7-9920-7820ac1cb311.png)

In general, it's not a great idea to truncate button labels unless absolutely necessary.  Seems like there is adequate white space in the list entry to fit the buttons without truncating.  It we are going to use a button to display details rather than the hyperlink of the object name, then recommend shortening the label to just "Details." It should be clear to the user that these are details of the object currently in view.

**Comment by gnehapk** [comment]
@mcarrano @julienlim Button label gets truncated if it doesn't have space enough to fit and the labels are visible on hover. On "100%" zoom, the button labels are visible properly. Attaching screenshot for the same. 

![screenshot from 2017-09-29 09-12-51](https://user-images.githubusercontent.com/5517376/31000025-72343be4-a4f6-11e7-92aa-f10628aabc5d.png)

So, when the page is getting zoomed in or out, the labels will adjust accordingly and gets truncated if it doesn't fit and are displayed on hovering. 

On task list page, since there are enough space, we will update it.

**Comment by a2batic** [comment]
@julienlim @mcarrano , Fixed with tendrl-ui-1.5.2-20171010T124450.4044474.noarch.rpm. Please verify

**Comment by julienlim** [comment]
Issue fixed and resolved.

![screen shot 2017-10-24 at 2 36 42 pm](https://user-images.githubusercontent.com/5589919/31961452-cacd88d8-b8c8-11e7-9363-f8ea43c98784.png)
