### ISSUE TITLE
Having 2 Alerts list and Notifications drawer are confusing

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#663]
Having 2 separate Alerts list and Notifications drawer are confusing because Alerts == Notifications since a user expects them to contain the same information.

* The original intent of the Alerts on the navigation menu was to provide a full view to see all event information, Alert details, filtering etc. (and from the Notification drawer, by clicking to see alert/notification details, you'd be taken to the details in the full view)
* Per @nthomas-redhat, the current implementation shows events in the Notification drawer, and alerts in the Alerts view

Based on the [Tendrl UI Optimized UX design](https://redhat.invisionapp.com/share/8QCOEVEY9), ideally what we should do is the following:
* Rename Alerts in the left-navigation menu to Events
* Rename Notification to Alerts
* Make the Notification Drawer (to be renamed Alerts Drawer) wider
* Show alerts in the Alerts Drawer
* Show all events in the Events view

![screen shot 2017-10-02 at 2 37 22 pm](https://user-images.githubusercontent.com/5589919/31181699-fbcceffc-a8ef-11e7-82e2-8acca40f952d.png)

@gnehapk @a2batic @Tendrl/tendrl-frontend @Tendrl/tendrl-qe @mcarrano

**Comment by julienlim** [comment]
Related issues:
* [UI Issues with Notification Drawer #629](https://github.com/Tendrl/ui/issues/629)
* [Notifications / Alerts in 2 places and have alerts that lack useful information #578](https://github.com/Tendrl/ui/issues/578)

**Comment by gnehapk** [comment]
As per the discussion with @nthomas-redhat we can swap the positions of "Alerts" and "Notifications" list. @brainfunked Need your confirmation.

**Comment by brainfunked** [comment]
There are two distinct entities: alert conditions and notifications.

Alert conditions are problem states that Tendrl detects and tracks. Examples of such states are node down, cluster down, currently existing threshold breach etc. Note the term *currently existing*. The alert conditions show up while they're present and have a life cycle. They can change state and can disappear altogether when the problem is fixed.

Notifications, on the other hand, are triggered based on events. As the term implies, they serve to notify the user of some event that occurs in the infrastructure. What this means is that there will be at least one notification per alert condition, but it is not necessary that a notification is for just an alert condition. A notification could also be for notifying of job updates or any other messages. Depending upon the severity, there could be one notification per state change for an alert condition.

Coming to the UI, the alerts tab is supposed to display alert conditions. This applies to the global as well as entity specific alerts tabs or panels. The number of alert conditions that exist for an entity are shown as 'alert count' in the list views, eg, for clusters. The notifications panel, however, is just for notifying the user of a particular event that has occurred.

With this context, here's what I feel needs to be reflected on the UX designs:

* The notifications should have some kind of an icon or colour scheme (or both) to indicate the nature of the event that has triggered the notification: alert condition state change, job status, generic (but important enough) log message etc.
* The terms 'events' and 'notifications' mean the same thing. The vertical drawer on the right needs to be named with either of these terms.
* The alerts tab should be called either 'alerts' or 'alert conditions' or some other better name, but it is neither for events nor for notifications. I would recommend clearly mentioning on the UI that the alert conditions listed in this tab are the ones that currently exist in the infrastructure.
* Notifications' lifecycle ends as soon as they're read. With this in mind, I don't think it is necessary to list so many notifications in the drawer. It would instead be better to devote more space to each notification to enable a clear display of the full message and icons and/or colours clearly indicating the nature of the notification. It is about quality, not the quantity. Notifications must be sorted by default to ensure that the most recent ones are at the top.

Please keep in mind that the notifications or events are not going to be stored any longer than a day or two. Alert conditions will be maintained and tracked as long as they exist. Logs are where both of these end up for permanent archival. As such, display of historic notifications is out of scope for tendrl presently.

**Comment by julienlim** [comment]
@brainfunked Thank you for your explanation of how it's currently implemented.  To sum up what you wrote:

Alert == current problems / conditions that Tendrl has detected and tracks.  Maintained and tracked as long as they exist.

Notifications == triggered based on events, 1 notification per alert, includes job updates, 1 notification per state change of an alert condition.  Analogous to events.  Not stored longer than a day or 2.

From an UX perspective, the term Alerts does indeed refer to current problems / conditions that the System tracks and that user cares to know about.

The Notifications the way it's implemented is more of a series of events (Event Log or syslog)

From a UX perspective, what is currently shown as Notifications (Drawer) was intended to showcase Alerts or current problems/conditions, but today it is showing what appears to showing the Event Log.  Users will expect them to be called Events or Log, hence why we recommend to put them on the left-nav menu.

For Alerts, the design of the Notification drawer was intended to showcase Alerts.

Hence my recommendation to swap the contents of Notifications (and relabel this as Events) and Alerts.

Furthermore, we've also made recommendations of the Notification Drawer implementation, i.e. to widen the drawer so that the relevant is more readable.  It was not fully implemented per design -- see https://redhat.invisionapp.com/share/8QCOEVEY9#/screens/244738613.

@gnehapk @nthomas-redhat @mcarrano @Tendrl/tendrl-qe

**Comment by brainfunked** [comment]
OK, that makes sense to me. A couple of comments on the design:

* It would be preferable to not truncate the alert messages. In a dashboard scenario, it's preferable to be able to see all the details at a glance rather than requiring mouse interaction.
* It would be good to be able to pin the panel on the right for permanent visibility across all views, drawn alongside the main view, rather than over it.

**Comment by gnehapk** [comment]
@julienlim Can you please mention the filters that will be applicable for the new event list view now and the event list will have just two columns(description and time stamp) for each event, since notification list has description and time stamp fields for each notification.
Also it seems that new alert list view(i.e. alert drawer) will don't have any filters now. Please confirm.

**Comment by julienlim** [comment]
@gnehapk @mcarrano @Tendrl/tendrl-qe 

For the Events list (aka notifications current), from looking at the JSON output using Tendrl-API, there are 4 fields: message_id, timestamp, priority, and message.  The 2 columns to be shown would be timestamp and message.  No filter needs to be applied except perhaps that the Events shown are specific to the selected cluster.  The Events list should be sorted in descending order of timestamp with the most recent event at the top.

For the Alerts list, the drawer needs to be wide enough to see the severity, alert message, and timestamp.  It is expected that the row entry of the data shown will wrap if the drawer is narrow in that all the data (severity + alert message + timestamp) is visible to the user.

If user wants to see More for the Alerts, ideally we should have the Alerts on the left nav (like we do have today), so users can see more details or click to see the full Alerts list (if the drawer only is able to show a partial list).

As the Alerts drawer can span all clusters, there would not be a filter.

The Alerts list in the Alerts drawer should be sorted in descending order of timestamp + severity with the most recent alert at the top.

**Comment by gnehapk** [comment]
@julienlim For event list page, we will display all the events sorted in the descending order of timestamp now. While implementing Concept B, events will be displayed specific to selected cluster.

**Comment by gnehapk** [comment]
@julienlim The alerts drawer adds a scrollbar if all the alerts are not able to fit into the given space. So, Is there any need of having alert list view on the left nav and if yes, which link/button will take the user to alert list page of left nav.

**Comment by julienlim** [comment]
@gnehapk I checked PatternFly, and there is a scrollbar for the Alerts drawer after all, so there is not a need after all to take you to Alerts list page in the left nav.

@mcarrano mentioned there's is a provision in the PF implementation to expand the drawer -- see http://www.patternfly.org/pattern-library/communication/notification-drawer/#/design for how to see the expanded view of Alerts.  We may need this later when additional Alerting features and capabilities are needed.

BTW, in our original design, we had a means for which to quickly filter alerts by severity level.  Will we have this in the drawer?

**Comment by mcarrano** [comment]
@gnehapk There is also code for the drawer expansion if you are able to leverage it.

**Comment by mcarrano** [comment]
@gnehapk I have refined the design a bit on severity filters in the drawer to allow for showing selection and clearing. See updated designs here: https://redhat.invisionapp.com/share/8QCOEVEY9#/244738613_Alerts_Drawer  If you click though to the next page. You will see what this should look like after a filter is applied and you can clear.  

Let me know if you have questions. @julienlim FYI

**Comment by gnehapk** [comment]
@julienlim @mcarrano Fixed with tendrl-ui-1.5.4-20171110T074803.fb3f1b1.noarch.rpm. Please verify.

**Comment by julienlim** [comment]
Fixed.  Some cosmetic issues (with extra lines) and hard to read full alert message, but other than that, the fix is verified.

<img width="1070" alt="screen shot 2017-11-10 at 10 46 53 am" src="https://user-images.githubusercontent.com/5589919/32666172-9bc11bec-c604-11e7-9c45-93a4d5b61f0f.png">

New issues created.
* https://github.com/Tendrl/ui/issues/744
* https://github.com/Tendrl/ui/issues/743

**Comment by ltrilety** [comment]
I have one observation here. Whilst alerts goes to the notifications drawer and notifications goes to events list, the drawer title and id is still Notifications not Alerts. Hence when I have a cursor over the bell it says Notifications.

**Comment by julienlim** [comment]
@ltrilety I put cursor over the bell, and it says Alerts.
![screen shot 2017-11-21 at 12 31 54 pm](https://user-images.githubusercontent.com/5589919/33087265-16202a3e-ceb8-11e7-83a6-e0fc3c6d7311.png)
