### ISSUE TITLE
Alert: severity filter was not implemented

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#665]
Per the (Alerts/Events design - Annotation #3](https://redhat.invisionapp.com/share/8QCOEVEY9#/screens/244738616), user should be able to click on the [alert icon][# of alerts] to filter to see alerts/events based the **# of alerts** clicked on.

Right now, it is not clickable.

In the screenshot example, I should be able to click on the 3 Warning icons to see a filtered list of the 3 warning items in the list.  The same applies to if I click on the 5 Informational icons, I should see the filtered list of information items in the list.

<img width="1173" alt="screen shot 2017-10-06 at 4 53 10 pm" src="https://user-images.githubusercontent.com/5589919/31298187-f264908c-aab6-11e7-8d9c-61e5c5fe3fc9.png">

@gnehapk @a2batic @Tendrl/tendrl-frontend @Tendrl/tendrl-qe @mcarrano

**Comment by cloudbehl** [comment]
@julienlim Currently don't have the patternfly filter implemented because it came in the later version of Patternfly and Upgrading the Patternfly version right now can create a race around conditions(I have tried upgrading the version the date pickers and the notifications stopped working). I don't know the exact impact of the upgrade but I am sure that the upgrade will hamper.

So the alternative for the approach is when we click on the Icon(warning or Alert) The Filter DropDown from should be selected to "Severity" and the text should be filled with "Warning", "Info" or "Alert".

@nthomas-redhat ^^

**Comment by julienlim** [comment]
@cloudbehl @mcarrano @nthomas-redhat @Tendrl/tendrl-qe 
Ack on upgrading to latest PatternFly causing race conditions and not wanting to do that at the moment.

The suggestion of adding Severity in the filter dropdown, where user fills in Warning, Info, Alert seems a reasonable compromise.

Thanks.

**Comment by gnehapk** [comment]
@julienlim  Fixed with tendrl-ui-1.5.3-20171024T073937.0815acd.noarch.rpm. Please verify.

**Comment by julienlim** [comment]
@gnehapk Verified that the severity filters in the filter dropdown works.

<img width="1210" alt="screen shot 2017-10-31 at 2 46 57 pm" src="https://user-images.githubusercontent.com/5589919/32243007-a414b18a-be4a-11e7-93e2-1f3f4458de3e.png">

<img width="1210" alt="screen shot 2017-10-31 at 2 46 45 pm" src="https://user-images.githubusercontent.com/5589919/32243018-ab02f79a-be4a-11e7-81c6-e544754a0487.png">
