### ISSUE TITLE
Null filter results returns unexpected response

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#718]
When I filter in the Alerts (and probably applies to all other places with filters), it should return the correct null filter response per PatternFly -- see https://www.patternfly.org/pattern-library/forms-and-controls/filter/#/design.

Currently, it says "No Alerts Detected." when filter returns null.

Current results:
![screen shot 2017-10-31 at 4 30 19 pm](https://user-images.githubusercontent.com/5589919/32247604-3c2bd580-be59-11e7-80d9-93ec1db14a96.png)

Expected results:
![screen shot 2017-10-31 at 4 31 59 pm](https://user-images.githubusercontent.com/5589919/32247615-42398b52-be59-11e7-8858-a89ef5d9b8bc.png)

@a2batic @gnehapk @cloudbehl @Tendrl/tendrl-qe @mcarrano

**Comment by gnehapk** [comment]
@julienlim Fixed with tendrl-ui-1.5.4-20171106T121612.853b7e1.noarch.rpm. Please verify.

**Comment by julienlim** [comment]
Fixed.

@gnehapk - Although fixed, the text does need revisiting as the text is not flowing well.

The suggested text: "Please try selecting other filter criteria." may need to be improved to "Try selecting a different filter criteria."
Clear All Filters <-- this does not need to be in bold text

<img width="1273" alt="screen shot 2017-11-10 at 10 03 39 am" src="https://user-images.githubusercontent.com/5589919/32664181-7bcc96aa-c5fe-11e7-8e74-fa7798323cec.png">

**Comment by a2batic** [comment]
@julienlim @mcarrano , Due to introduction of new filter component[1] by Angular patternfly 4, there is an additional 'Clear all filters' appearing after applying filter.

So, the views look like following now:-

1. Host/volume/brick/cluster/user
![screenshot from 2018-02-27 17-32-17](https://user-images.githubusercontent.com/12200504/36727705-47eef094-1be4-11e8-8723-89405553e99c.png)

2. Task 
![screenshot from 2018-02-27 17-24-29](https://user-images.githubusercontent.com/12200504/36727722-5283e046-1be4-11e8-9864-74c25ef77f2d.png)

3. Event
![screenshot from 2018-02-27 17-26-09](https://user-images.githubusercontent.com/12200504/36727732-5b800788-1be4-11e8-8979-047abca3d375.png)

- I discussed with patternfly team, the 'Clear all filters' in component cannot be removed from our side. So, it makes sense to remove 'Clear All filters' from empty/no results state.
- Also, for task list, status can be moved into filter component itself, https://github.com/Tendrl/ui/issues/843
- The filter component's "Clear all filters" will not clear dates, so we can add "Clear date" link to clear dates on Event/task view.

**Comment by a2batic** [comment]
@julienlim @mcarrano, please update the design according to the above changes.

**Comment by a2batic** [comment]
@julienlim, the issue has been fixed with the latest master build tendrl-ui-1.6.1-20180321T062725.a13280b.noarch.rpm, please verify.
