### ISSUE TITLE
Full alert message not visible to user without hovering on the message

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#744]
For Tendrl 1.5.4 (bugfixes) release, when looking at an alert message (in the Alert Drawer), it's not easy to see the full alert message without hovering over the text to see it.

<img width="1263" alt="screen shot 2017-11-10 at 10 16 58 am" src="https://user-images.githubusercontent.com/5589919/32664830-6b682c1e-c600-11e7-801a-bbaee7f7b991.png">

Is it possible to widen the Alert drawer or word wrap the alert message so it's more usable at-a-glance.  It will be challenging for users to look at multiple alerts at a glance to see what's going on, which may force users to use the API, use a JSON viewer to then reformat, etc. -- which defeats the use of the Alerting in the UI.

@gnehapk @a2batic @Tendrl/tendrl-frontend @Tendrl/tendrl-qe @nthomas-redhat @mcarrano

**Comment by gnehapk** [comment]
@julienlim Please suggest the width of alert drawer.

**Comment by julienlim** [comment]
@gnehapk Can you try doubling the width on the current Alert Drawer?

**Comment by gnehapk** [comment]
@julienlim Will remove the word wrap for the alert message so that the complete message will be visible to user at a glance.  I have tried doubling the width of the alert drawer. Its occupying more than half space of the content area. 
![expanded-alert-drawer](https://user-images.githubusercontent.com/5517376/32719084-1c71a11c-c885-11e7-9596-89c77f4d5e84.png)
 
Instead of this we can go for the expanded view of the alert drawer which toggles on click of icon. The
PF implementation of expanding the drawer(http://www.patternfly.org/pattern-library/communication/notification-drawer/#/design) is available in later version of 3.25.0(the current version).  We can plan to take this up in the next development cycle.

**Comment by julienlim** [comment]
@gnehapk The doubling width of the Alert Drawer doesn't look good, and agree going with expanded view of the Alert Drawer per PF would be better.

Not sure I understand you that "remove the word wrap for the alert message so complete message will be visible to user at a glance" -- will the alert message be completely visible?  If so wouldn't it need the word wrap to do so?  Do you have a screenshot of what you mean?  Thanks.

@mcarrano

**Comment by gnehapk** [comment]
@julienlim Sorry, I meant enabling the word wrap for alert message. Attaching the screenshot for the alert page after enabling the word wrap css property.
![alert-list](https://user-images.githubusercontent.com/5517376/32733773-38871e14-c8b6-11e7-868a-24f3d2219e26.png)

**Comment by julienlim** [comment]
@gnehapk Enabling word wrap looks good!  I'm looking forward to this landing in the release.

**Comment by a2batic** [comment]
@julienlim, this bug has been fixed with tendrl-ui-1.5.4-20171121T111815.8f8f468.noarch.rpm, please verify.

**Comment by gnehapk** [comment]
Closing this issue, as its been opened for quite long time. Please feel free to reopen if the issue still persists.
