### ISSUE TITLE
[RFE] Volume status does not reflect much information

### ISSUE THREAD

**Issue by a2batic** [Tendrl/ui#797]
Currently, the volume status icon conveys 'Started' or 'Stopped' status as per volume, it doesn't reflect appropriate status; for example when one of the brick is down or stopped, vol status still says 'Started'

![screenshot from 2018-02-02 15-58-14](https://user-images.githubusercontent.com/12200504/35729870-13c666e2-0836-11e8-809c-8af19a57eeee.png)

**Comment by a2batic** [comment]
@r0h4n @shtripat, what are the different scenarios that can be represented here as volume status?
@julienlim what should be the icons for various scenarios? Currently we have 'pficon-ok' for started and 'pficon-error-circle-o' for stopped.

**Comment by julienlim** [comment]
@a2batic @r0h4n @shtripat @Tendrl/tendrl-qe @mcarrano 

I recall wanting to reflect a "Degraded" state for the scenario when there are brick(s) down in a volume and the volume is still is online; however, I believe there are limited statuses for volumes available with get-state.  
 -- see https://github.com/Tendrl/ui/issues/728#issuecomment-342465798

* Volume possible status {"Created", "Started", "Stopped" }

The icons to use are detailed in the same issue: [Various status of bricks and corresponding icons](https://github.com/Tendrl/ui/issues/728)

**Comment by shtripat** [comment]
@julienlim so in tendrl based on logic borrowed from gstatus, we do maintain a field called `state` for volumes. The possible values for the volume state are `unknown` (till full volume details gets synced), `up`, `down`, `partial`, `degraded`.

If we have icons for all these states, we can actually the state in UI for volumes rather than using status values which supports only two values namely `Started` and `Stopped`.

**Comment by shtripat** [comment]
@aravindavk need your help on verifying the logic for calculating the volume state at https://github.com/Tendrl/gluster-integration/blob/master/tendrl/gluster_integration/sds_sync/cluster_status.py#L78. The logic is lifted from old gstatus as is and based on replica_count, disperse_count and redundancy_count values of various types of volumes it decides the volume state.

**Comment by julienlim** [comment]
@mcarrano Can you please confirm the status/state icon for "Degraded" for a Gluster volume?

In looking at some older designs for showing "degraded" on Gluster volumes, I found the icon in https://redhat.invisionapp.com/share/589XIRJBW#/screens/214068226.  Do we still want to use that or something else?

**Comment by mcarrano** [comment]
@julienlim Yes, it should be pficon-degraded (the one shown in the dashboard card you referenced).

**Comment by julienlim** [comment]
@mcarrano

Any thoughts on which icon to use for "Partial"?  See definition below.

Per https://github.com/gluster/gstatus:

UP(Degraded)
This state is specific to replicated volumes, where at least one brick is down within a replica set. Data is still 100% available due to the alternate replica(s),  but the resilience of the volume to further failures within the same replica set flags this volume as 'degraded'. 

UP(Partial)
Effectively this means that although some bricks in the volume are online, there are others that are down to a point where areas of the filesystem will be missing. For a distributed volume, this state is seen if ANY brick is down, whereas for a replicated volume a complete replica set needs to be down before the volume state transitions to PARTIAL.

**Comment by mcarrano** [comment]
@julienlim per our discussion, I have updated the Volumes list to indicate handling for this. See https://redhat.invisionapp.com/share/HVGA7O575AZ#/244738623_Cluster_Details-Volumes

In short, we will use the icon 'pficon-degraded' for both conditions, but Degraded will show in orange and Partial in red to indicate a more severe condition. When hovering, a tooltip will further explain the condition as detailed in the annotations. Let me know if you have any questions.

**Comment by julienlim** [comment]
@a2batic @gnehapk @nthomas-redhat  @r0h4n @shtripat @Tendrl/tendrl-qe @mcarrano See latest UX updates with regards to displaying degraded and partial state for the volume.

**Comment by a2batic** [comment]
@julienlim @mcarrano, what will be the icon for `unknown` (till full volume details gets synced) state ?

**Comment by julienlim** [comment]
@a2batic Unknown is the "?" (question mark) icon we've been using so far.  E.g. before a cluster is imported, it's got a "?" for unknown state.

**Comment by a2batic** [comment]
@mcarrano @julienlim, just to summarize:-
`unknown` : `fa-question` 
`up` : `pficon-ok`
`down` : `fa-arrow-circle-o-down`
`partial` : `pficon-degraded` red
`degraded`: `pficon-degraded` orange

**Comment by julienlim** [comment]
@a2batic That looks correct.

**Comment by a2batic** [comment]
Fixed in tendrl-ui-1.6.2-20180413T152054.8ff4c65.noarch.rpm.
