### ISSUE TITLE
Enhance Task Details

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#823]
Enhance Task Details to allow for showing multiple tasks within the same view through the use of a master-detail (table) design. Even if there is a single task, we should also follow this same design for consistency.

* [Task Details Design](https://redhat.invisionapp.com/share/8QCOEVEY9#/screens/277198377)
* Related mention: [Unmanage Cluster Spec](https://github.com/Tendrl/specifications/pull/255#issuecomment-366203195)

@a2batic @nthomas-redhat @mcarrano @Tendrl/tendrl-qe @gnehapk

**Comment by gnehapk** [comment]
As per @r0h4n and @nthomas-redhat comments, its difficult to send the task ids of both unmanage and import cluster task ids in API at the moment, so they have suggested to store it on the client side.

As per my knowledge, there are three ways to store data on client side - cookies, local storage and session storage. Storing data using the mentioned techniques is not reliable because of the following reason - 
- These client side data are not available across all the browsers. For eg- if you have stored the data in chrome, the same will not be available in firefox browser.
- Incognito mode don't have access to the stored client side data
- If someone clears the cookies from the browser, these data will be lost.
 
IMO getting the task ids from the API response is the ideal way to approach this issue. 
We will also explore other alternatives if any.

**Comment by julienlim** [comment]
@gnehapk @mcarrano @r0h4n @nthomas-redhat @Tendrl/qe 

 Per discussions in https://github.com/Tendrl/documentation/wiki/Architecture-Meeting-Notes (19 Feb 2018), unmanage and import cluster are going to be handled separately, so there's not a need to enhance task details at this phase of the release.  Let's keep Task Details as-is.  The [design](https://redhat.invisionapp.com/share/8QCOEVEY9#/screens/277198377) has been rolled back to the way it was.

This issue can be closed.  I'll leave you to close the issue after you've had a chance to read this comment.
